name: health_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.67.0
  pretty_gauge: ^1.0.1
  share_plus: ^7.2.2
  pie_chart: ^5.4.0

  simple_animation_progress_bar: ^1.8.2
  dotted_line: ^3.2.2
  dotted_dashed_line: ^0.0.3
  percent_indicator: ^4.2.3
  grouped_list: ^5.1.2
  intl: ^0.19.0
  http: ^1.2.0
  syncfusion_flutter_charts: ^25.1.41+2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/

  fonts:
     - family: Poppins
       fonts:
         - asset: assets/font/Poppins-Regular.ttf
         - asset: assets/font/Poppins-Bold.ttf
           weight: 700
